<?php
/**
 * Scheduled Blog Post Generator — OpenAI BATCH API
 *
 * Two-phase batch workflow:
 *   Phase 1: Generate content HTML for each topic (gpt-4o-mini, batch)
 *   Phase 2: Extract metadata (excerpt, meta_title, etc.) from content
 *   Final:   Insert all posts as drafts with scheduled published_at
 *
 * Reads topics from storage/topics_2026.json (generated by generate_topics.php).
 *
 * Usage:
 *   php scripts/generate_scheduled_posts.php prepare [--limit=92]
 *   php scripts/generate_scheduled_posts.php status
 *   php scripts/generate_scheduled_posts.php process
 *   php scripts/generate_scheduled_posts.php insert
 *   php scripts/generate_scheduled_posts.php run [--limit=92]
 */

require __DIR__ . '/../lib/database.php';
require __DIR__ . '/../lib/blog.php';

$config = require __DIR__ . '/../data/config.php';

$apiKey = $config['openai']['api_key'] ?? '';
$model  = 'gpt-4o-mini'; // Cost-efficient for batch content

if (empty($apiKey) || $apiKey === 'sk-proj-REPLACE_ME') {
    echo "[ERROR] OpenAI API key not configured\n";
    exit(1);
}

$stateFile   = __DIR__ . '/../storage/batch_scheduled_state.json';
$storageDir  = __DIR__ . '/../storage';
$topicsFile  = __DIR__ . '/../storage/topics_2026.json';

// --- Service mappings ---
$serviceImages = [
    'AI & ML'            => '/img/service-ai.jpg',
    'Custom Software'    => '/img/service-software.jpg',
    'Cloud & DevOps'     => '/img/service-cloud.jpg',
    'Digital Consulting' => '/img/service-consulting.jpg',
    'Cybersecurity'      => '/img/service-security.jpg',
    'Data & Analytics'   => '/img/service-data.jpg',
];
$servicePages = [
    'AI & ML'            => '/services/#ai-ml',
    'Custom Software'    => '/services/#custom-software',
    'Cloud & DevOps'     => '/services/#cloud-devops',
    'Digital Consulting' => '/services/#digital-consulting',
    'Cybersecurity'      => '/services/#cybersecurity',
    'Data & Analytics'   => '/services/#data-analytics',
];

// ─── Helper functions ────────────────────────────────────

function openai_request_scheduled(string $apiKey, string $method, string $endpoint, $body = null, string $contentType = 'application/json'): array
{
    $ch = curl_init("https://api.openai.com/v1{$endpoint}");
    $headers = ["Authorization: Bearer {$apiKey}"];

    if ($method === 'POST' && $body !== null) {
        curl_setopt($ch, CURLOPT_POST, true);
        if (is_array($body) && $contentType === 'multipart/form-data') {
            curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
        } else {
            curl_setopt($ch, CURLOPT_POSTFIELDS, is_string($body) ? $body : json_encode($body));
            $headers[] = "Content-Type: {$contentType}";
        }
    }

    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_TIMEOUT => 300,
    ]);

    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    return ['code' => $httpCode, 'body' => json_decode($response, true) ?? $response];
}

function openai_get_scheduled(string $apiKey, string $url): string
{
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HTTPHEADER => ["Authorization: Bearer {$apiKey}"],
        CURLOPT_TIMEOUT => 300,
    ]);
    $response = curl_exec($ch);
    curl_close($ch);
    return $response;
}

function load_state(string $file): array
{
    if (file_exists($file)) {
        return json_decode(file_get_contents($file), true) ?? [];
    }
    return [];
}

function save_state(string $file, array $state): void
{
    file_put_contents($file, json_encode($state, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
}

function clean_html(string $html): string
{
    $html = preg_replace('/<h1[^>]*>.*?<\/h1>/si', '', $html);
    $html = preg_replace('/<div[^>]*class=["\']prose["\'][^>]*>/si', '', $html);
    $html = preg_replace('/^```html?\s*/i', '', $html);
    $html = preg_replace('/\s*```\s*$/', '', $html);
    $html = preg_replace('/<\/div>\s*(<div class=["\']blog-cta)/si', '$1', $html);
    $html = preg_replace('/(\b\w+\b)(\s+\1){3,}/i', '$1', $html);
    return trim($html);
}

// ─── Prompts ─────────────────────────────────────────────

$contentSystemPrompt = <<<'SYSTEM'
You are a senior technology consultant at CDEM Solutions (cdemsolutions.com), a consultancy specializing in AI & Machine Learning, Custom Software Development, Cloud & DevOps, Digital Consulting, Cybersecurity, and Data & Analytics.

You write authoritative, in-depth blog articles that rank on Google.

## VOICE & TONE — CRITICAL
- Write as a senior consultant who has built real systems, NOT as an AI assistant.
- Use concrete examples with specific technologies, real companies, and actual metrics.
- NEVER use these clichés: "in today's rapidly evolving landscape", "cutting-edge", "game-changer", "revolutionize", "unlock the power of", "dive deep into", "navigate the complexities".
- Include at least ONE practical example or real-world case study per article.
- Write with authority and opinion. Take positions. Share lessons learned.

## OUTPUT FORMAT
Write ONLY raw HTML. No markdown. No JSON. No code fences. Just pure HTML content.

## REQUIRED STRUCTURE
1. Start with a `<nav class="toc">` containing a "Table of Contents" heading and an anchor-linked `<ul>` to each H2 section.
2. Write exactly **5 <h2> sections**, each with an `id` attribute matching the TOC anchors.
3. Under each H2, write **2 <h3> subsections**.
4. Under each H3, write **2-3 full paragraphs** (each paragraph 3-4 sentences).
5. End with a `<div class="blog-cta">` containing a CTA paragraph with a link to `/contact/`.
6. NEVER use `<h1>` tags.

## LENGTH REQUIREMENT
Your article MUST be **1,000–1,500 words**. Each H2 section should be ~200-300 words.
- Include numbered lists for processes, bullet lists for features/benefits.
- Add `<blockquote>` for key insights (1-2 per article).
- Use `<code>` for technical terms, commands, or snippets.
- Bold (`<strong>`) key concepts on first mention (6-8 per article).
- Include 2-3 internal links: `/services/`, `/contact/`, `/blog/` with descriptive anchor text.

## HTML TAGS ALLOWED
`<nav class="toc">`, `<h2 id="...">`, `<h3>`, `<p>`, `<ul>`, `<ol>`, `<li>`, `<strong>`, `<em>`, `<a>`, `<blockquote>`, `<code>`, `<pre><code>`, `<div class="blog-cta">`

Do NOT use: `<h1>`, `<img>`, `<table>`, `<span>`, `<br>`, inline styles, or any wrapper divs.

## SEO RULES
- H2/H3 headings must contain keywords naturally.
- First paragraph must include the primary keyword within 100 words.
- Use question-style H3 headings for featured snippets.

## DATE AWARENESS
NEVER reference events, tools, or versions released AFTER the publication date provided.
SYSTEM;

$metaSystemPrompt = <<<'SYSTEM'
You are an SEO specialist. Given an HTML blog article and its context, extract/create the metadata.
Return a JSON object with exactly these keys:
- "excerpt": Engaging summary for blog listing cards, 130-155 characters
- "meta_title": SEO title tag, 50-60 chars, primary keyword near start. Do NOT include "CDEM Solutions" — the site appends it automatically
- "meta_description": Action-oriented description, 150-160 chars, includes primary keyword
- "meta_keywords": 5-8 comma-separated keywords/phrases
SYSTEM;

// ─── COMMANDS ────────────────────────────────────────────

$command = $argv[1] ?? 'run';
$limit = 92;
foreach ($argv as $arg) {
    if (preg_match('/^--limit=(\d+)$/', $arg, $m)) {
        $limit = (int)$m[1];
    }
}

switch ($command) {

// ═════════════════════════════════════════════════════════
case 'prepare':
// ═════════════════════════════════════════════════════════
    echo "=== Phase 1: Preparing content batch ===\n";

    if (!file_exists($topicsFile)) {
        echo "[ERROR] Topics file not found: {$topicsFile}\n";
        echo "Run 'php scripts/generate_topics.php' first.\n";
        exit(1);
    }

    $topics = json_decode(file_get_contents($topicsFile), true);
    if (empty($topics)) {
        echo "[ERROR] No topics in {$topicsFile}\n";
        exit(1);
    }

    // Check which topics are already in the DB (by slug)
    $pdo = db();
    $existingSlugs = $pdo->query("SELECT slug FROM blog_posts")->fetchAll(PDO::FETCH_COLUMN);
    $existingSet = array_flip($existingSlugs);

    $pending = [];
    foreach ($topics as $topic) {
        if (isset($existingSet[$topic['slug']])) {
            continue; // Already created
        }
        $pending[] = $topic;
        if (count($pending) >= $limit) break;
    }

    if (empty($pending)) {
        echo "No new topics to process (all slugs already in DB).\n";
        exit(0);
    }

    echo "Topics to generate: " . count($pending) . " (skipped " . (count($topics) - count($pending)) . " existing)\n";

    // Build JSONL for content generation
    $jsonlFile = "{$storageDir}/batch_scheduled_content.jsonl";
    $fh = fopen($jsonlFile, 'w');
    $topicMap = [];

    foreach ($pending as $topic) {
        $customId = "topic-{$topic['index']}";
        $dateContext = date('F Y', strtotime($topic['scheduled_date']));
        $serviceUrl = $servicePages[$topic['service_category']] ?? '/services/';

        $userPrompt = "Write a blog article on this topic:\n\"{$topic['title']}\"\n\n"
            . "Context: {$topic['brief']}\n"
            . "Target service: {$topic['service_category']}\n"
            . "Publication date: {$dateContext} — do NOT reference anything after this date.\n"
            . "Service page URL: {$serviceUrl}\n\n"
            . "IMPORTANT:\n"
            . "- Write ONLY raw HTML. No markdown. No JSON wrapper. No code fences.\n"
            . "- Target 1,000–1,500 words across 5 H2 sections.\n"
            . "- Include at least one real-world example or case study.\n"
            . "- Write as a consultant sharing expertise, not as a content writer.\n"
            . "- Start with <nav class=\"toc\"> and end with <div class=\"blog-cta\">.";

        $line = json_encode([
            'custom_id' => $customId,
            'method' => 'POST',
            'url' => '/v1/chat/completions',
            'body' => [
                'model' => $model,
                'messages' => [
                    ['role' => 'system', 'content' => $contentSystemPrompt],
                    ['role' => 'user', 'content' => $userPrompt],
                ],
                'max_tokens' => 8000,
                'temperature' => 0.75,
                'top_p' => 0.95,
                'frequency_penalty' => 0.2,
                'presence_penalty' => 0.1,
            ],
        ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        fwrite($fh, $line . "\n");

        $topicMap[$customId] = $topic;
    }
    fclose($fh);
    echo "JSONL written: {$jsonlFile} (" . count($topicMap) . " requests)\n";

    // Upload file
    echo "Uploading JSONL to OpenAI...\n";
    $uploadResult = openai_request_scheduled($apiKey, 'POST', '/files', [
        'purpose' => 'batch',
        'file' => new CURLFile($jsonlFile, 'application/jsonl', 'batch_scheduled_content.jsonl'),
    ], 'multipart/form-data');

    if ($uploadResult['code'] !== 200 || !isset($uploadResult['body']['id'])) {
        echo "[ERROR] File upload failed: " . json_encode($uploadResult['body']) . "\n";
        exit(1);
    }

    $fileId = $uploadResult['body']['id'];
    echo "File uploaded: {$fileId}\n";

    // Create batch
    echo "Creating batch...\n";
    $batchResult = openai_request_scheduled($apiKey, 'POST', '/batches', [
        'input_file_id' => $fileId,
        'endpoint' => '/v1/chat/completions',
        'completion_window' => '24h',
        'metadata' => ['description' => 'CDEM 2026 scheduled blog content generation'],
    ]);

    if ($batchResult['code'] !== 200 || !isset($batchResult['body']['id'])) {
        echo "[ERROR] Batch creation failed: " . json_encode($batchResult['body']) . "\n";
        exit(1);
    }

    $batchId = $batchResult['body']['id'];
    echo "Batch created: {$batchId}\n";
    echo "Status: {$batchResult['body']['status']}\n";

    save_state($stateFile, [
        'phase' => 'content',
        'batch_id' => $batchId,
        'file_id' => $fileId,
        'topic_map' => $topicMap,
        'created_at' => date('Y-m-d H:i:s'),
    ]);

    echo "\nBatch submitted! Run 'php scripts/generate_scheduled_posts.php status' to check progress.\n";
    break;

// ═════════════════════════════════════════════════════════
case 'status':
// ═════════════════════════════════════════════════════════
    $state = load_state($stateFile);
    if (empty($state['batch_id'])) {
        echo "No active batch. Run 'prepare' first.\n";
        exit(1);
    }

    $response = openai_get_scheduled($apiKey, "https://api.openai.com/v1/batches/{$state['batch_id']}");
    $batch = json_decode($response, true);

    echo "Phase: {$state['phase']}\n";
    echo "Batch ID: {$state['batch_id']}\n";
    echo "Status: {$batch['status']}\n";

    $counts = $batch['request_counts'] ?? [];
    echo "Completed: " . ($counts['completed'] ?? 0) . " / " . ($counts['total'] ?? '?') . "\n";
    echo "Failed: " . ($counts['failed'] ?? 0) . "\n";

    if ($batch['status'] === 'completed') {
        echo "\nBatch complete! Output file: {$batch['output_file_id']}\n";
        if ($state['phase'] === 'content') {
            echo "Run 'php scripts/generate_scheduled_posts.php process' to continue.\n";
        } else {
            echo "Run 'php scripts/generate_scheduled_posts.php insert' to finish.\n";
        }
    }
    break;

// ═════════════════════════════════════════════════════════
case 'process':
// ═════════════════════════════════════════════════════════
    echo "=== Phase 2: Processing content & submitting metadata batch ===\n";

    $state = load_state($stateFile);
    if (empty($state['batch_id']) || $state['phase'] !== 'content') {
        echo "No content batch to process. Run 'prepare' first.\n";
        exit(1);
    }

    // Get batch info
    $response = openai_get_scheduled($apiKey, "https://api.openai.com/v1/batches/{$state['batch_id']}");
    $batch = json_decode($response, true);

    if ($batch['status'] !== 'completed') {
        echo "Batch not complete yet. Status: {$batch['status']}\n";
        exit(1);
    }

    $outputFileId = $batch['output_file_id'];
    echo "Downloading results from {$outputFileId}...\n";

    $outputContent = openai_get_scheduled($apiKey, "https://api.openai.com/v1/files/{$outputFileId}/content");

    $outputFile = "{$storageDir}/batch_scheduled_content_results.jsonl";
    file_put_contents($outputFile, $outputContent);

    // Parse results
    $lines = explode("\n", trim($outputContent));
    echo "Got " . count($lines) . " results.\n";

    $contentResults = [];
    $succeeded = 0;
    $failed = 0;

    foreach ($lines as $line) {
        $entry = json_decode($line, true);
        if (!$entry) continue;

        $customId = $entry['custom_id'];
        $response = $entry['response']['body'] ?? null;

        if (!$response || !isset($response['choices'][0]['message']['content'])) {
            $failed++;
            echo "  [FAIL] {$customId}: no content in response\n";
            continue;
        }

        $html = clean_html($response['choices'][0]['message']['content']);
        $wordCount = str_word_count(strip_tags($html));

        if ($wordCount < 200) {
            $failed++;
            echo "  [SKIP] {$customId}: too short ({$wordCount} words)\n";
            continue;
        }

        $contentResults[$customId] = $html;
        $succeeded++;
    }

    echo "Content parsed: {$succeeded} succeeded, {$failed} failed.\n\n";

    // Build metadata JSONL
    echo "Building metadata batch...\n";
    $metaJsonlFile = "{$storageDir}/batch_scheduled_meta.jsonl";
    $fh = fopen($metaJsonlFile, 'w');
    $metaCount = 0;

    foreach ($contentResults as $customId => $html) {
        $topicData = $state['topic_map'][$customId] ?? null;
        if (!$topicData) continue;

        $contentPreview = substr(strip_tags($html), 0, 1500);

        $userPrompt = "Blog article title: \"{$topicData['title']}\"\n"
            . "Service: {$topicData['service_category']}\n"
            . "Date: " . date('F Y', strtotime($topicData['scheduled_date'])) . "\n\n"
            . "Content preview (first 1500 chars):\n{$contentPreview}\n\n"
            . "Generate the metadata JSON for this article.";

        $line = json_encode([
            'custom_id' => $customId,
            'method' => 'POST',
            'url' => '/v1/chat/completions',
            'body' => [
                'model' => 'gpt-4o-mini',
                'messages' => [
                    ['role' => 'system', 'content' => $metaSystemPrompt],
                    ['role' => 'user', 'content' => $userPrompt],
                ],
                'max_tokens' => 500,
                'temperature' => 0.5,
                'response_format' => ['type' => 'json_object'],
            ],
        ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        fwrite($fh, $line . "\n");
        $metaCount++;
    }
    fclose($fh);
    echo "Metadata JSONL: {$metaCount} requests.\n";

    // Upload metadata JSONL
    echo "Uploading metadata JSONL...\n";
    $uploadResult = openai_request_scheduled($apiKey, 'POST', '/files', [
        'purpose' => 'batch',
        'file' => new CURLFile($metaJsonlFile, 'application/jsonl', 'batch_scheduled_meta.jsonl'),
    ], 'multipart/form-data');

    if ($uploadResult['code'] !== 200 || !isset($uploadResult['body']['id'])) {
        echo "[ERROR] Upload failed: " . json_encode($uploadResult['body']) . "\n";
        exit(1);
    }

    $metaFileId = $uploadResult['body']['id'];
    echo "File uploaded: {$metaFileId}\n";

    // Create metadata batch
    $batchResult = openai_request_scheduled($apiKey, 'POST', '/batches', [
        'input_file_id' => $metaFileId,
        'endpoint' => '/v1/chat/completions',
        'completion_window' => '24h',
        'metadata' => ['description' => 'CDEM 2026 scheduled blog metadata extraction'],
    ]);

    if ($batchResult['code'] !== 200 || !isset($batchResult['body']['id'])) {
        echo "[ERROR] Batch creation failed: " . json_encode($batchResult['body']) . "\n";
        exit(1);
    }

    $metaBatchId = $batchResult['body']['id'];
    echo "Metadata batch created: {$metaBatchId}\n";

    // Update state
    $state['phase'] = 'metadata';
    $state['batch_id'] = $metaBatchId;
    $state['meta_file_id'] = $metaFileId;
    $state['content_results'] = $contentResults;
    save_state($stateFile, $state);

    echo "\nMetadata batch submitted! Check with 'status', then run 'insert' when done.\n";
    break;

// ═════════════════════════════════════════════════════════
case 'insert':
// ═════════════════════════════════════════════════════════
    echo "=== Final: Inserting scheduled posts as drafts ===\n";

    $state = load_state($stateFile);
    if (empty($state['batch_id']) || $state['phase'] !== 'metadata') {
        echo "No metadata batch to process.\n";
        exit(1);
    }

    // Get batch info
    $response = openai_get_scheduled($apiKey, "https://api.openai.com/v1/batches/{$state['batch_id']}");
    $batch = json_decode($response, true);

    if ($batch['status'] !== 'completed') {
        echo "Metadata batch not complete. Status: {$batch['status']}\n";
        exit(1);
    }

    // Download metadata results
    $outputFileId = $batch['output_file_id'];
    echo "Downloading metadata results...\n";

    $outputContent = openai_get_scheduled($apiKey, "https://api.openai.com/v1/files/{$outputFileId}/content");

    file_put_contents("{$storageDir}/batch_scheduled_meta_results.jsonl", $outputContent);

    $lines = explode("\n", trim($outputContent));
    echo "Got " . count($lines) . " metadata results.\n";

    $pdo = db();
    $contentResults = $state['content_results'] ?? [];
    $topicMap = $state['topic_map'] ?? [];
    $inserted = 0;
    $errors = 0;

    foreach ($lines as $line) {
        $entry = json_decode($line, true);
        if (!$entry) continue;

        $customId = $entry['custom_id'];
        $html = $contentResults[$customId] ?? null;
        $topicData = $topicMap[$customId] ?? null;

        if (!$html || !$topicData) {
            $errors++;
            continue;
        }

        $metaContent = $entry['response']['body']['choices'][0]['message']['content'] ?? null;
        $meta = $metaContent ? json_decode($metaContent, true) : null;

        // Fallback metadata if extraction failed
        if (!$meta) {
            $meta = [
                'excerpt' => substr(strip_tags($html), 0, 155),
                'meta_title' => $topicData['title'],
                'meta_description' => substr(strip_tags($html), 0, 160),
                'meta_keywords' => implode(', ', $topicData['tags'] ?? []),
            ];
            echo "  [FALLBACK] {$customId}: using auto-generated metadata\n";
        }

        $featuredImage = $serviceImages[$topicData['service_category']] ?? '/img/service-consulting.jpg';
        $readingTime = blog_reading_time($html);

        $postData = [
            'title'            => $topicData['title'],
            'slug'             => $topicData['slug'],
            'excerpt'          => $meta['excerpt'] ?? '',
            'content_html'     => $html,
            'featured_image'   => $featuredImage,
            'status'           => 'draft',
            'meta_title'       => $meta['meta_title'] ?? '',
            'meta_description' => $meta['meta_description'] ?? '',
            'meta_keywords'    => $meta['meta_keywords'] ?? '',
            'reading_time'     => $readingTime,
            'author'           => 'CDEM Solutions',
            'published_at'     => $topicData['scheduled_date'],
        ];

        $postId = blog_create($postData);

        $tags = $topicData['tags'] ?? [];
        if (!empty($tags) && is_array($tags)) {
            blog_sync_tags($postId, $tags);
        }

        $inserted++;
        if ($inserted % 10 === 0) {
            echo "  Inserted {$inserted} drafts...\n";
        }
    }

    echo "\n===================================================\n";
    echo "  DONE! Inserted: {$inserted} | Errors: {$errors}\n";
    echo "===================================================\n";

    $draftCount = (int)$pdo->query("SELECT COUNT(*) FROM blog_posts WHERE status = 'draft'")->fetchColumn();
    $totalPosts = (int)$pdo->query("SELECT COUNT(*) FROM blog_posts")->fetchColumn();
    echo "Total drafts: {$draftCount}\n";
    echo "Total posts: {$totalPosts}\n";

    // Show next scheduled dates
    $stmt = $pdo->query("SELECT title, published_at FROM blog_posts WHERE status = 'draft' AND published_at IS NOT NULL ORDER BY published_at LIMIT 5");
    $upcoming = $stmt->fetchAll(PDO::FETCH_ASSOC);
    if ($upcoming) {
        echo "\nUpcoming scheduled posts:\n";
        foreach ($upcoming as $post) {
            $day = date('l', strtotime($post['published_at']));
            echo "  {$post['published_at']} ({$day}) — {$post['title']}\n";
        }
    }

    // Cleanup state
    unlink($stateFile);
    echo "\nState cleaned up.\n";
    break;

// ═════════════════════════════════════════════════════════
case 'run':
// ═════════════════════════════════════════════════════════
    echo "=== Full automated scheduled batch run ===\n\n";

    // Phase 1: Prepare
    echo "---- STEP 1: Prepare & submit content batch ----\n";
    passthru("php " . __FILE__ . " prepare --limit={$limit}");

    // Phase 2: Poll content batch
    echo "\n---- STEP 2: Waiting for content batch ----\n";
    $maxWait = 7200; // 2 hours max
    $waited = 0;
    $pollInterval = 30;

    while ($waited < $maxWait) {
        sleep($pollInterval);
        $waited += $pollInterval;

        $state = load_state($stateFile);
        if (empty($state['batch_id'])) {
            echo "  [ERROR] No batch ID in state\n";
            exit(1);
        }

        $response = openai_get_scheduled($apiKey, "https://api.openai.com/v1/batches/{$state['batch_id']}");
        $batch = json_decode($response, true);

        $counts = $batch['request_counts'] ?? [];
        $completed = $counts['completed'] ?? 0;
        $total = $counts['total'] ?? '?';
        $status = $batch['status'];

        $mins = round($waited / 60, 1);
        echo "  [{$mins}m] Status: {$status} | Progress: {$completed}/{$total}\n";

        if ($status === 'completed') {
            echo "  Content batch complete!\n\n";
            break;
        }
        if (in_array($status, ['failed', 'expired', 'cancelled'])) {
            echo "  [ERROR] Batch {$status}!\n";
            exit(1);
        }

        if ($waited > 300) $pollInterval = 60;
    }

    // Phase 3: Process content & submit metadata
    echo "---- STEP 3: Process content & submit metadata batch ----\n";
    passthru("php " . __FILE__ . " process");

    // Phase 4: Poll metadata batch
    echo "\n---- STEP 4: Waiting for metadata batch ----\n";
    $waited = 0;
    $pollInterval = 20;

    while ($waited < $maxWait) {
        sleep($pollInterval);
        $waited += $pollInterval;

        $state = load_state($stateFile);
        if (empty($state['batch_id'])) {
            echo "  [ERROR] No batch ID in state\n";
            exit(1);
        }

        $response = openai_get_scheduled($apiKey, "https://api.openai.com/v1/batches/{$state['batch_id']}");
        $batch = json_decode($response, true);

        $counts = $batch['request_counts'] ?? [];
        $completed = $counts['completed'] ?? 0;
        $total = $counts['total'] ?? '?';
        $status = $batch['status'];

        $mins = round($waited / 60, 1);
        echo "  [{$mins}m] Status: {$status} | Progress: {$completed}/{$total}\n";

        if ($status === 'completed') {
            echo "  Metadata batch complete!\n\n";
            break;
        }
        if (in_array($status, ['failed', 'expired', 'cancelled'])) {
            echo "  [ERROR] Batch {$status}!\n";
            exit(1);
        }
    }

    // Phase 5: Insert all posts
    echo "---- STEP 5: Inserting scheduled posts as drafts ----\n";
    passthru("php " . __FILE__ . " insert");

    echo "\nAll done! Posts are scheduled as drafts.\n";
    echo "Run the translation batch next: php scripts/translate_posts_batch.php run\n";
    break;

default:
    echo "Usage: php scripts/generate_scheduled_posts.php {prepare|status|process|insert|run} [--limit=92]\n";
    echo "\nCommands:\n";
    echo "  prepare  - Read topics, create JSONL, upload, submit content batch\n";
    echo "  status   - Check batch progress\n";
    echo "  process  - Download content, submit metadata batch\n";
    echo "  insert   - Download metadata, insert posts as drafts\n";
    echo "  run      - Do all steps automatically (waits for completion)\n";
    echo "\nOptions:\n";
    echo "  --limit=N  - Limit number of topics to process (default: 92)\n";
    echo "\nPrerequisite: Run 'php scripts/generate_topics.php' first.\n";
    break;
}
